name: api6-dev-container

services:
  app:
    container_name: api6-java
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    ports:
    - "8686:8080"
    volumes:
      - ../..:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
